optimizer: 'SGD'
dataset: 'fmnist/0.05_0'
num_sample: 1
weight_decay: 
- 0.0001
- 0.0001
lr: 0.005
epochs: 120
batch_size: 128
batch_log_interval: 50
train_limit: 500_000
lamda: 0.9
experiment: 
  name: 'KL_best'
  n_exp: 3
  n_trials: 1
  feedback: null
  regularizers:
    KL: 
    - 1.0
    - 1.0
  labeled_portion: u0
