template: true
optimizer: 'SGD'
dataset: 'kuairec_0'
num_sample: 14
lr: 0.01
epochs: 300
lr_sch: CosineAnnealingLR
batch_size: 256
batch_log_interval: 50
train_limit: 500_000
lse_lamda: 2.0
lamda: 0
experiment:
  name: '10n_full_lse_bandit_feedback_AR_ns14'
  n_exp: 10
  n_trials: 6
  feedback: 'bandit'
  regularizers:
    AlphaRenyi:
      type: 1
      beta: [0.001, 10]