template: true
optimizer: 'SGD'
dataset: 'fmnist_old/${TAU}_${UL}'
num_sample: 1
weight_decay: 
- 0.000001
- 0.000001
lr: 0.001
epochs: 300
batch_size: 128
batch_log_interval: 50
train_limit: 500_000
power_mean_lamda: 0.1
lamda: 0
experiment: 
  name: 'full_powermean_bandit_feedback'
  n_exp: 3
  n_trials: 3
  feedback: 'bandit'
  regularizers: null