template: true
optimizer: 'SGD'
dataset: 'emnist/${TAU}_${UL}'
num_sample: 1
weight_decay: 
- 0.0005
- 0.05
lr: 0.0005
epochs: 60
batch_size: 128
batch_log_interval: 50
train_limit: 500_000
lamda: 0
experiment: 
  name: 'DEEPLOG_full_ips_bandit_feedback_KL2'
  n_exp: 3
  n_trials: 6
  feedback: 'bandit'
  regularizers:
    KL2: 
    - 0.05
    - 5.0
