template: true
optimizer: 'SGD'
dataset: 'emnist_raw_linear/${TAU}_${UL}'
num_sample: 1
lr: 0.001
epochs: 300
batch_size: 256
batch_log_interval: 50
train_limit: 500_000
power_mean_lamda: 0.1
lamda: 0
experiment: 
  name: 'full_powermean_bandit_feedback_SM'
  n_exp: 3
  n_trials: 3
  feedback: 'bandit'
  regularizers:
    SM: 
    - 0.00001
    - 0.01