optimizer: 'SGD'
dataset: 'fmnist_f/0.2_4'
num_sample: 1
weight_decay: 
- 0.002
- 0.02
lr: 0.005
epochs: 120
batch_size: 128
batch_log_interval: 50
train_limit: 500_000
lamda: 0
experiment: 
  name: 'ips_full_bandit_feedback_KL2'
  n_exp: 3
  n_trials: 10
  feedback: 'bandit'
  regularizers:
    KL2: 
    - 0.01
    - 2.0
  labeled_portion: u4
