optimizer: 'SGD'
dataset: 'fmnist_f/0.2_4'
num_sample: 1
weight_decay: 
- 0.001
- 0.01
lr: 0.005
epochs: 120
batch_size: 128
batch_log_interval: 50
train_limit: 500_000
lamda: 0
experiment: 
  name: 'ips_full_bandit_feedback'
  n_exp: 3
  n_trials: 5
  feedback: 'bandit'
  regularizers: null
  labeled_portion: u4
