optimizer: 'SGD'
dataset: 'fmnist_f/0.2_0'
num_sample: 1
weight_decay: 
<<<<<<< HEAD
<<<<<<< HEAD:code/config/fmnist/tau5/ul0/ips_bandit_KL2.yaml
- 0.001
- 0.05
=======
- 0.0001
- 0.0001
>>>>>>> 673c86560494b2826f6a68af8348b414d1e7f043:code/config/cifar/tau20/ul0/KL.yaml
=======
- 0.001
- 0.05
>>>>>>> 673c86560494b2826f6a68af8348b414d1e7f043
lr: 0.005
epochs: 120
batch_size: 128
batch_log_interval: 50
train_limit: 500_000
lamda: 0
experiment: 
<<<<<<< HEAD
<<<<<<< HEAD:code/config/fmnist/tau5/ul0/ips_bandit_KL2.yaml
=======
>>>>>>> 673c86560494b2826f6a68af8348b414d1e7f043
  name: 'full_ips_bandit_feedback_KL2'
  n_exp: 3
  n_trials: 10
  feedback: 'bandit'
  regularizers:
    KL2: 
    - 0.05
    - 5.0
<<<<<<< HEAD
=======
  name: 'KL_best'
  n_exp: 3
  n_trials: 1
  feedback: null
  regularizers:
    KL:
    - 1.0
    - 1.0
>>>>>>> 673c86560494b2826f6a68af8348b414d1e7f043:code/config/cifar/tau20/ul0/KL.yaml
=======
>>>>>>> 673c86560494b2826f6a68af8348b414d1e7f043
  labeled_portion: u0
