optimizer: 'SGD'
dataset: 'fmnist_f/0.2_0'
num_sample: 1
weight_decay: 
<<<<<<< HEAD
- 0.001
- 0.02
=======
<<<<<<< HEAD:code/config/cifar/tau5/ul0/KL.yaml
- 0.0001
- 0.0001
=======
- 0.001
- 0.02
>>>>>>> 673c86560494b2826f6a68af8348b414d1e7f043:code/config/fmnist/tau5/ul0/ips_bandit.yaml
>>>>>>> 673c86560494b2826f6a68af8348b414d1e7f043
lr: 0.005
epochs: 120
batch_size: 128
batch_log_interval: 50
train_limit: 500_000
lamda: 0
experiment: 
<<<<<<< HEAD
=======
<<<<<<< HEAD:code/config/cifar/tau5/ul0/KL.yaml
  name: 'KL_best'
  n_exp: 3
  n_trials: 1
  feedback: null
  regularizers:
    KL:
    - 1.0
    - 1.0
=======
>>>>>>> 673c86560494b2826f6a68af8348b414d1e7f043
  name: 'full_ips_bandit_feedback'
  n_exp: 3
  n_trials: 5
  feedback: 'bandit'
  regularizers: null
<<<<<<< HEAD
=======
>>>>>>> 673c86560494b2826f6a68af8348b414d1e7f043:code/config/fmnist/tau5/ul0/ips_bandit.yaml
>>>>>>> 673c86560494b2826f6a68af8348b414d1e7f043
  labeled_portion: u0
