optimizer: 'SGD'
dataset: 'fmnist_f/0.2_49'
num_sample: 1
weight_decay: 
<<<<<<< HEAD
- 0.0002
- 0.005
=======
<<<<<<< HEAD:code/config/cifar/tau5/ul49/KL2.yaml
- 0.0001
- 0.0001
=======
- 0.0002
- 0.005
>>>>>>> 673c86560494b2826f6a68af8348b414d1e7f043:code/config/fmnist/tau5/ul49/ips_bandit_KL.yaml
>>>>>>> 673c86560494b2826f6a68af8348b414d1e7f043
lr: 0.005
epochs: 120
batch_size: 128
batch_log_interval: 50
train_limit: 500_000
lamda: 0
experiment: 
<<<<<<< HEAD
=======
<<<<<<< HEAD:code/config/cifar/tau5/ul49/KL2.yaml
  name: 'KL2_best'
  n_exp: 3
  n_trials: 1
  feedback: null
  regularizers:
    KL2:
    - 1.0
    - 1.0
=======
>>>>>>> 673c86560494b2826f6a68af8348b414d1e7f043
  name: 'ips_full_bandit_feedback_KL'
  n_exp: 3
  n_trials: 10
  feedback: 'bandit'
  regularizers:
    KL: 
    - 0.05
    - 5.0
<<<<<<< HEAD
=======
>>>>>>> 673c86560494b2826f6a68af8348b414d1e7f043:code/config/fmnist/tau5/ul49/ips_bandit_KL.yaml
>>>>>>> 673c86560494b2826f6a68af8348b414d1e7f043
  labeled_portion: u49
