optimizer: 'SGD'
dataset: 'fmnist/1.0_4'
num_sample: 1
weight_decay: 
- 0.005
- 0.01
lr: 0.005
epochs: 120
batch_size: 128
batch_log_interval: 50
train_limit: 500_000
lamda: 0.9
experiment: 
  name: 'full_bandit_feedback_KL_best'
  n_exp: 3
  n_trials: 6
  feedback: 'bandit'
  regularizers:
    KL:
    - 0.5
    - 10.0
  labeled_portion: u4
